const swaggerAutogen = require('swagger-autogen')()

const outputFile = './swagger_output.json'
const endpointsFiles = ['./routes/api.route']

const doc = {
    info: {
        version: "1.0.0",
        title: "My API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:5000",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    basePath: '/api',
    securityDefinitions: {
        bearerAuth: {
            type: 'apiKey',
            name: 'Authorization', // Use the correct header name
            scheme: 'bearer',
            in: 'header',
        },
    },
    security: [{ bearerAuth: [] }] // Apply bearerAuth globally
}

swaggerAutogen(outputFile, endpointsFiles, doc)
    